%YAML 1.2
---
HTTPServer:
    daemonize: True
    no_keep_alive: True
    ports: [8080,8081, 8082] 
    xheaders: True
    debug: True
    logdir: 'logs'
    logformat: '%(levelname)s   %(asctime)s %(name)s PID(%(process)d) %(message)s'

Logging:
    directory: 'logs'
    filename: 'MinistryOfPackages.log'
    format: '%(levelname)s   %(asctime)s %(name)s PID(%(process)d) %(message)s'
    # Valid values: debug, info, warning, error, critical
    level: debug
    #handler: syslog
    #syslog:
    #    address: '/dev/log'
    #    facility: local6

Application:
    PackageDirs:
    # Path relative to the main app directory, (by default, 'main app directory' == /opt/MinistryOfPackages)
        - packages
    static_path: __base_path__/static
    template_path: __base_path__/templates

# Changing the layout here. This will allow for 
# easy expansion into more complex configs for 
# RequestHandlers. 
RequestHandlers:
 - MinistryOfPackages.handlers.SetupPyHandler:
    url: "/dist"
 - MinistryOfPackages.handlers.SetupPyHandler:
    url: "/pypi"
 - MinistryOfPackages.handlers.PyPIHandler:
    url: "/index/(?P<package>.*)/(?P<version>.*)"
 - MinistryOfPackages.handlers.DirectoryListingHandler:
    url: "/(?P<directory>.+)"
 - MinistryOfPackages.handlers.PyPIHandler:
    url: "/"

